# Generated by Django 4.1 on 2023-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airplane",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("passengers", models.PositiveIntegerField()),
            ],
        ),
    ]
